Fix Crowdin...

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -78,7 +78,7 @@ jobs:
           name: Deploy v1 Website
           # Skip the deploy if we don't have the right org (facebook), or if this is just a pull request
           command: |
-            if ! git diff-tree --no-commit-id --name-only -r HEAD | grep -E "(docusaurus-1\.x\/.*)|(website-1\.x\/.*)"; then
+            if ! git diff-tree --no-commit-id --name-only -r HEAD | grep -E "(crowdin-v1.yml)|(docusaurus-1\.x\/.*)|(website-1\.x\/.*)"; then
               echo "Skipping deploy. No relevant v1 website files have changed"
             elif [[ $CIRCLE_PROJECT_USERNAME == "facebook" && -z $CIRCLE_PR_USERNAME ]]; then
               echo "Deploying website v1..."
@@ -88,9 +88,12 @@ jobs:
               yarn run write-translations
 
               # upload translation strings and download translations
-              # TODO we have a weird Crowdin error "Project already contains the file", trying to resolve that with support
-              # In the meantime we should not block the v1 site deployment
-              yarn crowdin-upload || echo "Crowdin source upload failure, but we'll continue..."
+              # IMPORTANT: if this fails due to a Crowdin error like "Project already contains the file"
+              # Sometimes Crowdin refuse to upload the new versioned docs for obscure reasons
+              # Workaround: upload manually the new versioned files through the Crowdin UI...
+              # If the files already exist on Crowdin, the source upload will now work...
+              # All this has been extensively reported to their support already.
+              yarn crowdin-upload
 
               # download only enabled languages
               yarn crowdin-download
